function expr = Model(t,in2,in3)
%Model
%    EXPR = Model(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    25-Sep-2022 15:08:46

A = in2(5,:);
C = in2(6,:);
D = in2(2,:);
E = in2(7,:);
I = in2(3,:);
Q = in2(8,:);
R = in2(1,:);
S = in2(4,:);
param58 = in3(:,1);
param59 = in3(:,2);
param60 = in3(:,3);
param61 = in3(:,4);
param62 = in3(:,5);
param63 = in3(:,6);
param64 = in3(:,7);
param65 = in3(:,8);
param66 = in3(:,9);
param67 = in3(:,10);
param68 = in3(:,11);
t2 = A.*param68;
t3 = I.*param60;
t4 = Q.*param64;
t5 = Q.*param65;
t6 = E.^2;
t7 = S.^2;
t8 = A.*S.*param62;
t9 = A.*S.*param67;
t10 = C.*S.*param62;
t11 = D.*S.*param62;
t12 = E.*S.*param62;
t13 = I.*S.*param59;
t14 = I.*S.*param62;
t15 = Q.*S.*param62;
t16 = R.*S.*param62;
t18 = A+C+D+E+I+Q+R+S;
t17 = param62.*t7;
t19 = 1.0./t18;
mt1 = [t5;t4;t2-t3+E.*param63;-t19.*(t8+t9+t10+t11+t12+t13+t14+t15+t16+t17+param58.*t7+A.*S.*param58+C.*S.*param58+D.*S.*param58+E.*S.*param58+I.*S.*param58+Q.*S.*param58+R.*S.*param58);-t2+E.*param61;-C.*param66+S.*param58];
mt2 = [t19.*(t8+t9+t10+t11+t12+t13+t14+t15+t16+t17-param61.*t6-param63.*t6+C.^2.*param66+A.*C.*param66-A.*E.*param61-A.*E.*param63+C.*D.*param66-C.*E.*param61-C.*E.*param63+C.*E.*param66-D.*E.*param61-D.*E.*param63+C.*I.*param66-E.*I.*param61-E.*I.*param63+C.*Q.*param66+C.*R.*param66+C.*S.*param66-E.*Q.*param61-E.*Q.*param63-E.*R.*param61-E.*R.*param63-E.*S.*param61-E.*S.*param63);t3-t4-t5];
expr = [mt1;mt2];
