function expr = Model(t,in2,in3)
%Model
%    EXPR = Model(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Dec-2022 09:06:59

A = in2(5,:);
C = in2(6,:);
D = in2(2,:);
E = in2(7,:);
I = in2(3,:);
Q = in2(8,:);
R = in2(1,:);
S = in2(4,:);
param12 = in3(:,1);
param13 = in3(:,2);
param14 = in3(:,3);
param15 = in3(:,4);
param16 = in3(:,5);
param17 = in3(:,6);
param18 = in3(:,7);
param19 = in3(:,8);
param20 = in3(:,9);
param21 = in3(:,10);
param22 = in3(:,11);
t2 = A.*param22;
t3 = I.*param14;
t4 = Q.*param18;
t5 = Q.*param19;
t6 = E.^2;
t7 = S.^2;
t8 = A.*S.*param16;
t9 = A.*S.*param21;
t10 = C.*S.*param16;
t11 = D.*S.*param16;
t12 = E.*S.*param16;
t13 = I.*S.*param13;
t14 = I.*S.*param16;
t15 = Q.*S.*param16;
t16 = R.*S.*param16;
t18 = A+C+D+E+I+Q+R+S;
t17 = param16.*t7;
t19 = 1.0./t18;
mt1 = [t5;t4;t2-t3+E.*param17;-t19.*(t8+t9+t10+t11+t12+t13+t14+t15+t16+t17+param12.*t7+A.*S.*param12+C.*S.*param12+D.*S.*param12+E.*S.*param12+I.*S.*param12+Q.*S.*param12+R.*S.*param12);-t2+E.*param15;-C.*param20+S.*param12];
mt2 = [t19.*(t8+t9+t10+t11+t12+t13+t14+t15+t16+t17-param15.*t6-param17.*t6+C.^2.*param20+A.*C.*param20-A.*E.*param15-A.*E.*param17+C.*D.*param20-C.*E.*param15-C.*E.*param17+C.*E.*param20-D.*E.*param15-D.*E.*param17+C.*I.*param20-E.*I.*param15-E.*I.*param17+C.*Q.*param20+C.*R.*param20+C.*S.*param20-E.*Q.*param15-E.*Q.*param17-E.*R.*param15-E.*R.*param17-E.*S.*param15-E.*S.*param17);t3-t4-t5];
expr = [mt1;mt2];
