function expr = Model(t,in2,in3)
%MODEL
%    EXPR = MODEL(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    26-Sep-2021 11:06:20

A = in2(5,:);
C = in2(6,:);
D = in2(2,:);
E = in2(7,:);
I = in2(3,:);
Q = in2(8,:);
R = in2(1,:);
S = in2(4,:);
param1 = in3(:,1);
param2 = in3(:,2);
param3 = in3(:,3);
param4 = in3(:,4);
param5 = in3(:,5);
param6 = in3(:,6);
param7 = in3(:,7);
param8 = in3(:,8);
param9 = in3(:,9);
param10 = in3(:,10);
param11 = in3(:,11);
t2 = A.*param11;
t3 = I.*param3;
t4 = Q.*param7;
t5 = Q.*param8;
t6 = E.^2;
t7 = S.^2;
t8 = A.*S.*param5;
t9 = A.*S.*param10;
t10 = C.*S.*param5;
t11 = D.*S.*param5;
t12 = E.*S.*param5;
t13 = I.*S.*param2;
t14 = I.*S.*param5;
t15 = Q.*S.*param5;
t16 = R.*S.*param5;
t18 = A+C+D+E+I+Q+R+S;
t17 = param5.*t7;
t19 = 1.0./t18;
expr = [t5;t4;t2-t3+E.*param6;-t19.*(t8+t9+t10+t11+t12+t13+t14+t15+t16+t17+param1.*t7+A.*S.*param1+C.*S.*param1+D.*S.*param1+E.*S.*param1+I.*S.*param1+Q.*S.*param1+R.*S.*param1);-t2+E.*param4;-C.*param9+S.*param1;t19.*(t8+t9+t10+t11+t12+t13+t14+t15+t16+t17-param4.*t6-param6.*t6+C.^2.*param9+A.*C.*param9-A.*E.*param4-A.*E.*param6+C.*D.*param9-C.*E.*param4-C.*E.*param6+C.*E.*param9-D.*E.*param4-D.*E.*param6+C.*I.*param9-E.*I.*param4-E.*I.*param6+C.*Q.*param9+C.*R.*param9+C.*S.*param9-E.*Q.*param4-E.*Q.*param6-E.*R.*param4-E.*R.*param6-E.*S.*param4-E.*S.*param6);t3-t4-t5];
