function expr = Model(t,in2,in3)
%MODEL
%    EXPR = MODEL(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    26-Sep-2021 11:17:08

He = in2(6,:);
Hi = in2(2,:);
Hr = in2(4,:);
Hs = in2(5,:);
Me = in2(3,:);
Mi = in2(8,:);
Ms = in2(7,:);
param12 = in3(:,1);
param13 = in3(:,2);
param14 = in3(:,3);
param15 = in3(:,4);
param16 = in3(:,5);
param17 = in3(:,6);
param18 = in3(:,7);
t2 = He.*param17;
t3 = Hi.*param14;
t4 = Me+Mi+Ms;
t5 = Hi.*Ms.*param13;
t6 = He.*Me.*2.0;
t7 = He.*Mi.*2.0;
t8 = He.*Ms.*2.0;
t9 = Hs.*Mi.*param12.*5.0;
t10 = He+Hi+Hr+Hs;
t11 = -t9;
t12 = 1.0./t4;
t13 = 1.0./t10;
expr = [t2;Hi.*(-2.0./5.0)+t2-t3;-t13.*(-t5+He.*Me.*param16+He.*Me.*param18+Hi.*Me.*param16+Hi.*Me.*param18+Hr.*Me.*param16+Hr.*Me.*param18+Hs.*Me.*param16+Hs.*Me.*param18);Hr.*(-2.0./5.0)+t3;(t12.*(t6+t7+t8+t11+Hi.*Me.*2.0+Hi.*Mi.*2.0+Hr.*Me.*2.0+Hr.*Mi.*2.0+Hi.*Ms.*2.0+Hr.*Ms.*2.0))./5.0;t12.*(t6+t7+t8+t11+Me.*t2.*5.0+Mi.*t2.*5.0+Ms.*t2.*5.0).*(-1.0./5.0);-t13.*(t5-He.*param15-Hi.*param15-Hr.*param15-Hs.*param15+He.*Ms.*param16+Hi.*Ms.*param16+Hr.*Ms.*param16+Hs.*Ms.*param16);Me.*param18-Mi.*param16];
