function expr = Mode0P(t,in2,in3)
%Mode0P
%    EXPR = Mode0P(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    22-Sep-2022 16:39:11

E = in2(3,:);
He = in2(10,:);
Hi = in2(1,:);
Hr = in2(2,:);
Hs = in2(9,:);
L = in2(4,:);
Me = in2(7,:);
Mi = in2(8,:);
Ms = in2(6,:);
P = in2(5,:);
param57 = in3(:,1);
param58 = in3(:,2);
param59 = in3(:,3);
param60 = in3(:,4);
param61 = in3(:,5);
param62 = in3(:,6);
param63 = in3(:,7);
param64 = in3(:,8);
param65 = in3(:,9);
param66 = in3(:,10);
param67 = in3(:,11);
param68 = in3(:,12);
param69 = in3(:,13);
param70 = in3(:,14);
param71 = in3(:,15);
param72 = in3(:,16);
param73 = in3(:,17);
t2 = Hi.*param64;
t3 = L.*param65;
t4 = Me+Mi+Ms;
t5 = He.*Me.*param68;
t6 = He.*Mi.*param68;
t7 = He.*Ms.*param68;
t8 = Hs.*Mi.*param59;
t9 = Hi.*Ms.*param60;
t10 = He+Hi+Hr+Hs;
t11 = -t8;
t12 = 1.0./t4;
t13 = 1.0./t10;
mt1 = [-t2+He.*param72-Hi.*param68;t2-Hr.*param68;-(E.*Me.*param61+E.*Mi.*param61+E.*Ms.*param61+E.*param57.*param63+E.*param57.*param67-Me.*param57.*param61-Mi.*param57.*param61-Ms.*param57.*param61)./param57;-t3+E.*param63-L.*param69;t3-P.*param66-P.*param71;-t13.*(t9+He.*Ms.*param70+Hi.*Ms.*param70+Hr.*Ms.*param70+Hs.*Ms.*param70-He.*P.*param62.*param66-Hi.*P.*param62.*param66-Hr.*P.*param62.*param66-Hs.*P.*param62.*param66);-t13.*(-t9+He.*Me.*param73+Hi.*Me.*param73+Hr.*Me.*param73+Hs.*Me.*param73+He.*Me.*param58.*param70+Hi.*Me.*param58.*param70+Hr.*Me.*param58.*param70+Hs.*Me.*param58.*param70);Me.*param73-Mi.*param58.*param70];
mt2 = [t12.*(t5+t6+t7+t11+Hi.*Me.*param68+Hi.*Mi.*param68+Hr.*Me.*param68+Hr.*Mi.*param68+Hi.*Ms.*param68+Hr.*Ms.*param68);-t12.*(t5+t6+t7+t11+He.*Me.*param72+He.*Mi.*param72+He.*Ms.*param72)];
expr = [mt1;mt2];
