function expr = Model(t,in2,in3)
%Model
%    EXPR = Model(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    29-Oct-2022 17:20:31

He = in2(6,:);
Hi = in2(2,:);
Hr = in2(4,:);
Hs = in2(5,:);
Me = in2(3,:);
Mi = in2(8,:);
Ms = in2(7,:);
param1 = in3(:,1);
param2 = in3(:,2);
param3 = in3(:,3);
param4 = in3(:,4);
param5 = in3(:,5);
param6 = in3(:,6);
param7 = in3(:,7);
t2 = He.*param6;
t3 = Hi.*param3;
t4 = He.*Me;
t5 = He.*Mi;
t6 = He.*Ms;
t7 = Me+Mi+Ms;
t8 = Hi.*Ms.*param2;
t9 = He+Hi+Hr+Hs;
t11 = Hs.*Mi.*param1.*2.5e+3;
t10 = 1.0./t7;
t12 = 1.0./t9;
t13 = -t11;
expr = [t2;Hi.*(-4.0e-4)+t2-t3;-t12.*(-t8+param5.*t4+param7.*t4+Hi.*Me.*param5+Hi.*Me.*param7+Hr.*Me.*param5+Hr.*Me.*param7+Hs.*Me.*param5+Hs.*Me.*param7);Hr.*(-4.0e-4)+t3;(t10.*(t4+t5+t6+t13+Hi.*Me+Hi.*Mi+Hr.*Me+Hr.*Mi+Hi.*Ms+Hr.*Ms))./2.5e+3;t10.*(t4+t5+t6+t13+Me.*t2.*2.5e+3+Mi.*t2.*2.5e+3+Ms.*t2.*2.5e+3).*(-4.0e-4);-t12.*(t8-He.*param4-Hi.*param4-Hr.*param4-Hs.*param4+param5.*t6+Hi.*Ms.*param5+Hr.*Ms.*param5+Hs.*Ms.*param5);Me.*param7-Mi.*param5];
