function expr = Model(t,in2,in3)
%Model
%    EXPR = Model(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    10-Oct-2022 14:55:02

He = in2(6,:);
Hi = in2(2,:);
Hr = in2(4,:);
Hs = in2(5,:);
Me = in2(3,:);
Mi = in2(8,:);
Ms = in2(7,:);
param56 = in3(:,1);
param57 = in3(:,2);
param58 = in3(:,3);
param59 = in3(:,4);
param60 = in3(:,5);
param61 = in3(:,6);
param62 = in3(:,7);
t2 = He.*param61;
t3 = Hi.*param58;
t4 = He.*Me;
t5 = He.*Mi;
t6 = He.*Ms;
t7 = Me+Mi+Ms;
t8 = Hi.*Ms.*param57;
t9 = He+Hi+Hr+Hs;
t11 = Hs.*Mi.*param56.*2.5e+3;
t10 = 1.0./t7;
t12 = 1.0./t9;
t13 = -t11;
expr = [t2;Hi.*(-4.0e-4)+t2-t3;-t12.*(-t8+param60.*t4+param62.*t4+Hi.*Me.*param60+Hi.*Me.*param62+Hr.*Me.*param60+Hr.*Me.*param62+Hs.*Me.*param60+Hs.*Me.*param62);Hr.*(-4.0e-4)+t3;(t10.*(t4+t5+t6+t13+Hi.*Me+Hi.*Mi+Hr.*Me+Hr.*Mi+Hi.*Ms+Hr.*Ms))./2.5e+3;t10.*(t4+t5+t6+t13+Me.*t2.*2.5e+3+Mi.*t2.*2.5e+3+Ms.*t2.*2.5e+3).*(-4.0e-4);-t12.*(t8-He.*param59-Hi.*param59-Hr.*param59-Hs.*param59+param60.*t6+Hi.*Ms.*param60+Hr.*Ms.*param60+Hs.*Ms.*param60);Me.*param62-Mi.*param60];
