function expr = Model(t,in2,in3)
%Model
%    EXPR = Model(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    27-Nov-2022 19:55:33

A = in2(5,:);
C = in2(6,:);
D = in2(2,:);
E = in2(7,:);
I = in2(3,:);
Q = in2(8,:);
R = in2(1,:);
S = in2(4,:);
param52 = in3(:,1);
param53 = in3(:,2);
param54 = in3(:,3);
param55 = in3(:,4);
param56 = in3(:,5);
param57 = in3(:,6);
param58 = in3(:,7);
param59 = in3(:,8);
param60 = in3(:,9);
param61 = in3(:,10);
param62 = in3(:,11);
t2 = A.*param62;
t3 = I.*param54;
t4 = Q.*param58;
t5 = Q.*param59;
t6 = E.^2;
t7 = S.^2;
t8 = A.*S.*param56;
t9 = A.*S.*param61;
t10 = C.*S.*param56;
t11 = D.*S.*param56;
t12 = E.*S.*param56;
t13 = I.*S.*param53;
t14 = I.*S.*param56;
t15 = Q.*S.*param56;
t16 = R.*S.*param56;
t18 = A+C+D+E+I+Q+R+S;
t17 = param56.*t7;
t19 = 1.0./t18;
mt1 = [t5;t4;t2-t3+E.*param57;-t19.*(t8+t9+t10+t11+t12+t13+t14+t15+t16+t17+param52.*t7+A.*S.*param52+C.*S.*param52+D.*S.*param52+E.*S.*param52+I.*S.*param52+Q.*S.*param52+R.*S.*param52);-t2+E.*param55;-C.*param60+S.*param52];
mt2 = [t19.*(t8+t9+t10+t11+t12+t13+t14+t15+t16+t17-param55.*t6-param57.*t6+C.^2.*param60+A.*C.*param60-A.*E.*param55-A.*E.*param57+C.*D.*param60-C.*E.*param55-C.*E.*param57+C.*E.*param60-D.*E.*param55-D.*E.*param57+C.*I.*param60-E.*I.*param55-E.*I.*param57+C.*Q.*param60+C.*R.*param60+C.*S.*param60-E.*Q.*param55-E.*Q.*param57-E.*R.*param55-E.*R.*param57-E.*S.*param55-E.*S.*param57);t3-t4-t5];
expr = [mt1;mt2];
