function expr = Model(t,in2,in3)
%Model
%    EXPR = Model(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    25-Sep-2022 15:19:41

A = in2(5,:);
C = in2(6,:);
D = in2(2,:);
E = in2(7,:);
I = in2(3,:);
Q = in2(8,:);
R = in2(1,:);
S = in2(4,:);
param113 = in3(:,1);
param114 = in3(:,2);
param115 = in3(:,3);
param116 = in3(:,4);
param117 = in3(:,5);
param118 = in3(:,6);
param119 = in3(:,7);
param120 = in3(:,8);
param121 = in3(:,9);
param122 = in3(:,10);
param123 = in3(:,11);
t2 = A.*param123;
t3 = I.*param115;
t4 = Q.*param119;
t5 = Q.*param120;
t6 = E.^2;
t7 = S.^2;
t8 = A.*S.*param117;
t9 = A.*S.*param122;
t10 = C.*S.*param117;
t11 = D.*S.*param117;
t12 = E.*S.*param117;
t13 = I.*S.*param114;
t14 = I.*S.*param117;
t15 = Q.*S.*param117;
t16 = R.*S.*param117;
t18 = A+C+D+E+I+Q+R+S;
t17 = param117.*t7;
t19 = 1.0./t18;
mt1 = [t5;t4;t2-t3+E.*param118;-t19.*(t8+t9+t10+t11+t12+t13+t14+t15+t16+t17+param113.*t7+A.*S.*param113+C.*S.*param113+D.*S.*param113+E.*S.*param113+I.*S.*param113+Q.*S.*param113+R.*S.*param113);-t2+E.*param116;-C.*param121+S.*param113];
mt2 = [t19.*(t8+t9+t10+t11+t12+t13+t14+t15+t16+t17-param116.*t6-param118.*t6+C.^2.*param121+A.*C.*param121-A.*E.*param116-A.*E.*param118+C.*D.*param121-C.*E.*param116-C.*E.*param118+C.*E.*param121-D.*E.*param116-D.*E.*param118+C.*I.*param121-E.*I.*param116-E.*I.*param118+C.*Q.*param121+C.*R.*param121+C.*S.*param121-E.*Q.*param116-E.*Q.*param118-E.*R.*param116-E.*R.*param118-E.*S.*param116-E.*S.*param118);t3-t4-t5];
expr = [mt1;mt2];
